import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require(process.env.H3_PLAYWRIGHT||'playwright');
const cfg=JSON.parse(await readFile(new URL('../work/qa-v08-config.json',import.meta.url),'utf8'));
const output=new URL('../work/qa-v08-ui/',import.meta.url);await mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const shot=name=>page.screenshot({path:new URL(name+'.png',output).pathname.replace(/^\/([A-Za-z]:)/,'$1')});
try{
 await page.goto(process.env.H3_TEST_URL||'http://127.0.0.1:8789');
 await page.waitForFunction(()=>document.querySelector('#image-model').options.length>1);
 await page.evaluate(()=>localStorage.clear());await page.reload();
 await page.click(`[data-chat="${cfg.body}"]`);await page.waitForSelector('.message.assistant audio');
 assert.equal(await page.locator('.message.assistant audio').count(),1);
 const audio=page.locator('.message.assistant audio');await audio.evaluate(a=>new Promise((resolve,reject)=>{if(a.readyState>=1)return resolve();a.onloadedmetadata=resolve;a.onerror=reject;}));
 assert.ok(await audio.evaluate(a=>a.duration)>80);
 await audio.evaluate(a=>{a.currentTime=30});await page.waitForFunction(()=>document.querySelector('.message.assistant audio').currentTime>=29);
 const download=page.locator('.message.assistant .audio-output a');assert.match(await download.getAttribute('download'),/Morning Light.*wav/);
 await page.click('#music-toggle');assert.equal(await page.getAttribute('#music-toggle','aria-pressed'),'true');
 await page.locator('#music-inputs').evaluate(e=>e.open=true);
 await page.fill('[data-music-field="title"]','La mia prova');await page.fill('[data-music-field="style"]','warm acoustic pop');await page.fill('[data-music-field="lyrics"]','[Verse]\nUn giorno nuovo');
 await page.uncheck('#image-assistant');await page.reload();await page.click(`[data-chat="${cfg.body}"]`);await page.waitForFunction(()=>document.querySelector('#chat-title').textContent==='Musica in chat');await page.waitForFunction(()=>document.querySelector('#music-toggle').getAttribute('aria-pressed')==='true');
 assert.equal(await page.getAttribute('#music-toggle','aria-pressed'),'true');assert.equal(await page.isChecked('#image-assistant'),false);
 await page.locator('#music-inputs').evaluate(e=>e.open=true);assert.equal(await page.inputValue('[data-music-field="lyrics"]'),'[Verse]\nUn giorno nuovo');
 await shot('chat-player');
 await page.click('#music-toggle');await page.click(`[data-chat="${cfg.canvas}"]`);
 await page.click('#canvas-toggle');await page.waitForSelector('#canvas-preview audio');
 assert.equal(await page.locator('.message.assistant audio').count(),0);assert.equal(await page.locator('.message.assistant .music-composition').count(),0);
 assert.match(await page.locator('#canvas-preview').innerText(),/Sunlight spills/);
 await shot('canvas');
 await page.click('#settings-open');await page.waitForSelector('#music-link');
 assert.equal(await page.inputValue('[data-setting="music_model"]'),cfg.music);
 await page.check('#music-advanced');
 assert.equal(await page.inputValue('[data-music-setting="num_inference_steps"]'),'32');assert.equal(await page.inputValue('[data-music-setting="seed"]'),'831001');
 assert.equal(await page.inputValue('[data-music-setting="cot"]'),'full');
 await page.fill('[data-music-setting="num_inference_steps"]','24');await page.click('#settings-save');
 await page.click('#settings-open');assert.equal(await page.inputValue('[data-music-setting="num_inference_steps"]'),'24');
 await page.click('#music-reset');assert.equal(await page.inputValue('[data-music-setting="num_inference_steps"]'),'32');
 await page.locator('#music-link').scrollIntoViewIfNeeded();await shot('admin-music');
 await page.click('#music-link');assert.equal(await page.inputValue('#local-model-kind'),'yue2');assert.equal(await page.locator('[data-browse-role]').count(),2);
 await page.click('[data-browse-role="model"]');await page.waitForSelector('.browser-entry');await page.click('#model-browser-close');await page.click('#local-model-close');
 await page.click('#settings-save');
 await page.setViewportSize({width:430,height:932});await shot('mobile');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 assert.deepEqual(errors,[]);console.log('Music UI passed: WAV duration/seek/download, Music and Assistant persistence, canvas-only output, presets and filesystem.');
}finally{await browser.close();}
