import {createRequire} from 'node:module';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.H3_PLAYWRIGHT||'playwright');
const paths=JSON.parse(await readFile(new URL('../work/external-fixtures.json',import.meta.url),'utf8'));
const out=new URL('../work/qa-v04-ui/',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1');
await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const check=(value,message)=>{if(!value)throw Error(message);};
try{
 await page.goto(process.env.H3_TEST_URL||'http://127.0.0.1:8788');
 await page.waitForFunction(()=>document.querySelector('#think-note').textContent.length>0);
 await page.click('#settings-open');await page.click('[data-tab="models"]');
 await page.click('#add-external-model');
 await page.route('**/api/model-files/browse',async route=>{if(route.request().postDataJSON()?.path==='')await new Promise(r=>setTimeout(r,500));await route.continue();});
 await page.click('[data-browse-role="model"]');
 await page.fill('#model-browser-path',paths.llm.replace(/[\\/][^\\/]+$/,''));
 await new Promise(r=>setTimeout(r,700));
 check((await page.locator('#model-browser-path').inputValue())===paths.llm.replace(/[\\/][^\\/]+$/,''),'Initial listing overwrote pasted directory');
 await page.locator('#model-browser-address button').click();
 await page.locator('.browser-entry').filter({hasText:'model.gguf'}).click();
 await page.waitForFunction(()=>document.querySelector('#local-model-hint').textContent.includes('file trovato'));
 await page.screenshot({path:out+'/link-llm.png'});
 await page.click('#local-model-save');await page.waitForFunction(()=>!document.querySelector('#local-model-dialog').open);
 await page.waitForSelector('[data-external-card]');
 let state=await page.evaluate(async()=>await(await fetch('/api/state')).json());
 const llm=state.models.find(m=>m.external&&m.external_config.files.model===paths.llm.replaceAll('/','\\'))||state.models.find(m=>m.external&&m.name==='LLM esterno test');
 check(llm?.vision?.enabled&&llm.ready,'LLM/projector not linked');
 await page.click('#add-external-model');await page.selectOption('#local-model-kind','flux2');
 await page.fill('#local-model-name','FLUX esterno test');
 await page.fill('[data-local-role="diffusion"]',paths.diffusion);
 await page.fill('[data-local-role="llm"]',paths.llm_encoder);
 await page.fill('[data-local-role="vae"]',paths.vae);
 await page.screenshot({path:out+'/link-images.png'});
 await page.click('#local-model-save');await page.waitForFunction(()=>!document.querySelector('#local-model-dialog').open);
 state=await page.evaluate(async()=>await(await fetch('/api/state')).json());
 const flux=state.models.find(m=>m.external&&m.name==='FLUX esterno test');check(flux?.ready,'Image components not linked');
 await page.click('[data-tab="setup"]');
 await page.selectOption('[data-setting="chat_model"]',llm.id);
 await page.selectOption('[data-setting="create_model"]',flux.id);
 await page.selectOption('[data-setting="edit_model"]',flux.id);
 await page.click('#settings-save');await page.waitForFunction(()=>!document.querySelector('#settings').open);
 state=await page.evaluate(async()=>await(await fetch('/api/state')).json());
 check(state.settings.chat_model===llm.id&&state.settings.create_model===flux.id&&state.settings.edit_model===flux.id,'External selections not saved');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#vision-badge').textContent==='Vision attiva');
 await page.click('#settings-open');await page.click('[data-tab="models"]');
 await page.click(`[data-edit-external="${llm.id}"]`);
 await page.selectOption('#local-projector-mode','manual');
 await page.fill('[data-local-role="mmproj"]',paths.mmproj);
 await page.click('#local-model-save');await page.waitForFunction(()=>!document.querySelector('#local-model-dialog').open);
 await page.setViewportSize({width:390,height:844});await page.click(`[data-edit-external="${flux.id}"]`);
 await page.screenshot({path:out+'/mobile-link.png'});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');
 await page.click('#local-model-close');await page.setViewportSize({width:1440,height:1080});
 await page.click(`[data-remove-external="${llm.id}"]`);
 await page.waitForFunction(id=>!document.querySelector(`[data-external-card="${id}"]`),llm.id);
 await page.click(`[data-remove-external="${flux.id}"]`);
 await page.waitForFunction(id=>!document.querySelector(`[data-external-card="${id}"]`),flux.id);
 check((await readFile(paths.llm)).length>0&&(await readFile(paths.vae)).length>0,'Unlink deleted original files');
 check(errors.length===0,'Browser errors: '+errors.join(';'));
 await writeFile(out+'/external-result.json',JSON.stringify({passed:true,llm:llm.id,image:flux.id,errors},null,2));
 console.log('External browser picker, auto/manual mmproj, image components across directories, selection, persistence, unlink and mobile layout passed.');
}catch(error){console.log(await page.evaluate(()=>({path:document.querySelector('#model-browser-path')?.value,error:document.querySelector('#model-browser-error')?.textContent,list:document.querySelector('#model-browser-list')?.textContent})));throw error;}finally{await browser.close();}
