import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.H3_PLAYWRIGHT||'playwright');
const out=new URL('../work/qa-v02/',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1');
await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR: '+e.stack);});
const check=(value,message)=>{if(!value)throw Error(message);};
try{
 await page.goto(process.env.H3_TEST_URL||'http://127.0.0.1:8788');
 await page.waitForFunction(()=>document.querySelector('#think-note').textContent.length>0);
 await page.click('#settings-open');
 await page.selectOption('[data-setting="profile"]','balanced');
 await page.selectOption('[data-setting="backend"]','vulkan');
 await page.selectOption('[data-setting="chat_model"]','qwen3-4');
 await page.selectOption('[data-setting="edit_model"]','flux2-klein4');
 await page.waitForSelector('.memory-result');
 await page.waitForFunction(()=>document.querySelectorAll('.memory-result').length===2);
 const memory=await page.locator('#memory-assessment').innerText();
 check(memory.includes('RAM')&&memory.includes('VRAM'),'Missing memory measurements');
 await page.locator('#memory-assessment').scrollIntoViewIfNeeded();
 await page.screenshot({path:out+'/memory.png'});
 await page.selectOption('[data-setting="profile"]','cpu');
 await page.selectOption('[data-setting="chat_model"]','smolvlm');
 check((await page.locator('#setup-vision-note').innerText()).includes('Vision attiva'),'Projector not detected');
 await page.click('#settings-save');
 await page.waitForFunction(()=>document.querySelector('#vision-badge').textContent==='Vision attiva');
 check(await page.locator('#think-level').isDisabled(),'Unsupported thinking must be disabled');
 await page.click('#settings-open');
 await page.selectOption('[data-setting="chat_model"]','qwen3-06');
 await page.click('#settings-save');
 await page.waitForFunction(()=>!document.querySelector('#think-level').disabled);
 check(await page.locator('#vision-warning').isVisible(),'Non-vision warning not visible');
 check((await page.locator('#vision-badge').innerText())==='Non vision','Incorrect vision badge');
 for(const level of ['off','low','med','high','xhigh']){
  console.log('Testing Think '+level);
  await page.selectOption('#think-level',level);
  await page.waitForFunction(()=>!document.querySelector('#think-level').disabled);
  const value=await page.evaluate(async()=> (await (await fetch('/api/state')).json()).settings.think_level);
  check(value===level,'Thinking setting not persisted: '+level);
 }
 await page.selectOption('#think-level','low');
 await page.waitForFunction(()=>!document.querySelector('#think-level').disabled);
 console.log('Sending real CPU request');
 await page.click('#new-chat');await page.waitForSelector('.chat-row.active');
 await page.fill('#prompt','Calcola 17 per 19. Rispondi solo con il risultato.');
 await page.click('#send');
 await page.waitForSelector('.message.assistant .message-actions button',{timeout:180000});
 const answer=await page.locator('.message.assistant .message-content').innerText();
 check(answer.includes('323'),'Incorrect real thinking answer: '+answer);
 check(!answer.includes('<think>'),'Reasoning tags leaked into body');
 check((await page.locator('.message.assistant .message-head').innerText()).includes('Think low'),'Thinking metadata missing');
 await page.screenshot({path:out+'/chat.png'});
 await page.reload();await page.waitForFunction(()=>document.querySelector('#think-level').value==='low');
 await page.click('#settings-open');await page.click('[data-tab="models"]');
 await page.click('#rescan-models');await page.waitForSelector('#rescan-models');
 await page.screenshot({path:out+'/models.png'});await page.click('#settings-close');
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:out+'/mobile.png'});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow on mobile');
 check(errors.length===0,errors.join('\n'));
 await writeFile(out+'/result.json',JSON.stringify({answer,memory,errors},null,2));
 console.log(JSON.stringify({ok:true,answer,errors}));
}catch(e){console.error(JSON.stringify({errors}));await page.screenshot({path:out+'/failure.png',timeout:5000}).catch(()=>{});throw e;}finally{await browser.close();}
