"""Collect retained upstream licenses for the private native music runtime."""
import argparse,hashlib,json,shutil
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--source',type=Path,required=True);p.add_argument('--output',type=Path,required=True);args=p.parse_args()
args.output.mkdir(parents=True,exist_ok=True)
files={'audio.cpp':'LICENSE','ggml':'external/ggml/LICENSE','sentencepiece':'external/sentencepiece/LICENSE','protobuf-lite':'external/sentencepiece/third_party/protobuf-lite/LICENSE','esaxx':'external/sentencepiece/third_party/esaxx/LICENSE','darts-clone':'external/sentencepiece/third_party/darts_clone/LICENSE','absl':'external/sentencepiece/third_party/absl/LICENSE','cJSON':'external/cJSON/LICENSE','libyaml':'external/libyaml/License','cpp-httplib':'external/cpp-httplib/LICENSE'}
for name,relative in files.items():shutil.copyfile(args.source/relative,args.output/(name+'-LICENSE.txt'))
(args.output/'NOTICE.txt').write_text('H3-Chat private YuE2 worker. audio.cpp commit 13c4192a28d6a212f075c4cbefc5e4983e6ed52a (Apache-2.0), H3 artifact patch in native/music/h3-artifacts.patch.\nMicrosoft Visual C++ Runtime DLLs are unmodified redistributables: https://visualstudio.microsoft.com/license-terms/vs2022-cruntime/\nCUDA dependencies are downloaded separately from NVIDIA, retain their licenses and are not covered by the application license: https://docs.nvidia.com/cuda/eula/index.html\nModel weights are not included. YuE2 weights: CC BY-NC 4.0.\n',encoding='utf-8')
root=Path(__file__).resolve().parents[1]
(args.output/'SOURCES.json').write_text(json.dumps({'audio.cpp':{'commit':'13c4192a28d6a212f075c4cbefc5e4983e6ed52a','archive':'https://codeload.github.com/0xShug0/audio.cpp/zip/13c4192a28d6a212f075c4cbefc5e4983e6ed52a','sha256':'7bdd528f8f0ec176823fb478ee7f03dbb8fdbd628f63f669ff281fe100b5a2dd'},'worker_sha256':hashlib.sha256((root/'native/music/worker.cpp').read_bytes()).hexdigest(),'patch_sha256':hashlib.sha256((root/'native/music/h3-artifacts.patch').read_bytes()).hexdigest(),'cuda_architectures':'75-virtual;120-real','build':'scripts/build-music-runtime.ps1','license':'Apache-2.0 audio.cpp, MIT H3 wrapper, separate upstream notices'},indent=2),encoding='utf-8')
