import '../static/infographic-motion.js';
const encode=deck=>'```h3-slides\n'+JSON.stringify(deck)+'\n```';
const $=s=>document.querySelector(s);
const choices={video_start:[['together','Insieme'],['panel','All’ingresso del pannello']],layout:[['full','Intero'],['columns2','2 affiancati'],['rows2','2 sopra / sotto'],['columns3','3 affiancati'],['rows3','3 sopra / sotto'],['pip','Principale + riquadro']],panel_appearance:[['all','Tutti insieme'],['sequence','In sequenza']],panel_order:[['auto','1 → 2 → 3 · auto'],['12','12'],['21','21'],['123','123'],['132','132'],['213','213'],['231','231'],['312','312'],['321','321']],corners:[['square','Dritti'],['soft','Morbidi'],['round','Arrotondati']],frame:[['dark','Scuro'],['light','Chiaro']],style:[['auto','Automatico'],['professional','Professionale'],['playful','Giocoso'],['comic','Fumetto'],['editorial','Editoriale'],['advert','Spot'],['tech','Tecnologico']],palette:[['auto','Dal prompt'],['natural','Naturale'],['pastel','Pastello'],['vivid','Vivace'],['neon','Neon'],['dark','Scura']],shapes:[['auto','Automatiche'],['soft','Morbide'],['sharp','Nette'],['mixed','Miste']],pace:[['auto','Automatico'],['calm','Calmo'],['dynamic','Dinamico'],['spot','Energico']],images:[['auto','Automatiche'],['provided','Allegati / galleria'],['generate','Genera con AI']],music:[['auto','Dal prompt'],['none','Nessuna'],['uploaded','Audio allegato'],['generate','Genera base'],['jingle','Jingle cantato']],sfx:[['none','Nessuno'],['subtle','Discreti'],['strong','Marcati']],voice_style:[['auto','Automatica'],['serious','Seria'],['lively','Vivace'],['spot','Spot'],['warm','Calda'],['radio','Radio · +8–12%']],transition:[['auto','Automatiche'],['cut','Taglio'],['fade','Dissolvenza'],['slide','Scorrimento'],['zoom','Zoom'],['wipe','Tendina']],output:[['video','Video animato'],['static','Statica']]};
const labels={video_start:'Partenza dei video',layout:'Composizione dello schermo',panel_appearance:'Comparsa dei riquadri',panel_order:'Ordine di comparsa',corners:'Angoli del video',video_background:'Sfondo video',video_fit:'Adattamento',video_end:'Se il video è più corto',video_audio:'Audio del filmato',frame:'Sfondo degli angoli',style:'Stile',palette:'Palette',shapes:'Forme',pace:'Ritmo',images:'Immagini',music:'Musica',sfx:'Effetti sonori',voice_style:'Recitazione',transition:'Transizioni',output:'Risultato'};
export function initInfographics({getState,getAttachments=()=>[],uploadVideo,notify=()=>{}}){
 const panel=document.createElement('section');panel.id='infographic-options';panel.hidden=true;panel.className='prompt-slide-options';
 panel.innerHTML='<p class="small-note">Regia automatica dal prompt e dalle fonti. Aggiungi immagini tue o lascia che vengano generate tutte insieme.</p>';
 const select=(key,items)=>{const field=document.createElement('div');field.className='prompt-field';field.dataset.infographicField=key;field.innerHTML='<span class="prompt-field-label">'+(labels[key]||'Formato')+'</span>';const group=document.createElement('div');group.className='prompt-choices';group.ariaLabel=labels[key]||'Formato';let value=key==='sfx'?'subtle':items[0][0];
  for(const [id,label] of items){const button=document.createElement('button');button.type='button';button.className='prompt-choice';button.textContent=label;button.dataset.value=id;button.setAttribute('aria-pressed',String(id===value));button.onclick=()=>{value=id;for(const b of group.children)b.setAttribute('aria-pressed',String(b===button));if(['layout','panel_appearance'].includes(key))renderScreen();};group.append(button);}field.append(group);panel.append(field);return ()=>value;
 };
 const reads={format:select('format',[['9:16','9:16'],['16:9','16:9'],['1:1','1:1'],['4:3','4:3'],['16:10','16:10']])};for(const key of ['layout','panel_appearance','panel_order','style','images','output','corners'])reads[key]=select(key,choices[key]);
 panel.insertAdjacentHTML('beforeend','<label class="field" data-panel-interval><span>Intervallo fra ingressi · secondi</span><input data-info="panel_interval" type="number" min="0.2" max="30" step="0.1" value="0.8"></label><p class="small-note">Riquadri numerati da sinistra a destra, oppure dall’alto in basso. Con Principale + riquadro: 1 principale, 2 sovraimpressione. L’LLM compone contenuti ed effetti; l’ordine scelto viene rispettato anche nelle scene brevi.</p>');
 function renderScreen(){const count={columns2:2,rows2:2,columns3:3,rows3:3,pip:2}[reads.layout()]||1,order=panel.querySelector('[data-infographic-field="panel_order"]'),sequence=count>1&&reads.panel_appearance()==='sequence';panel.querySelector('[data-infographic-field="panel_appearance"]').hidden=count===1;order.hidden=!sequence;panel.querySelector('[data-panel-interval]').hidden=!sequence;const start=panel.querySelector('[data-infographic-field="video_start"]');if(start)start.hidden=count===1||!getAttachments().some(m=>m.mime==='video/mp4');for(const b of order.querySelectorAll('button')){b.hidden=b.dataset.value!=='auto'&&b.dataset.value.length!==count;if(b.dataset.value==='auto')b.textContent='123'.slice(0,count).split('').join(' → ')+' · auto';}if(reads.panel_order()!=='auto'&&reads.panel_order().length!==count)order.querySelector('[data-value="auto"]').click();}
 const videoPanel=document.createElement('section');videoPanel.className='infographic-advanced';videoPanel.innerHTML='<h3 class="prompt-settings-heading">Video di sfondo · allegato o galleria</h3><p class="small-note">MP4 fino a 64 MB. Il filmato prosegue fra le scene: testi e grafiche vengono sovrapposti senza deformarlo. Vision analizza il primo fotogramma. In split screen puoi allegare fino a tre video: il prompt indica quali usare nei riquadri; solo il principale può mantenere il suo audio.</p><button type="button" class="btn" data-video-upload>＋ Allega video</button><input type="file" accept="video/mp4,.mp4" hidden data-video-file><label class="field"><span>Video principale</span><select data-info="video_id"><option value="">Nessun video allegato</option></select></label>';panel.append(videoPanel);
 for(const [key,items] of Object.entries({video_background:[['auto','Usa il video allegato'],['off','Senza video']],video_fit:[['contain','Mostra intero'],['cover','Riempi · ritaglia']],video_start:choices.video_start,video_end:[['freeze','Ferma l’ultimo fotogramma'],['loop','Ripeti']],video_audio:[['mute','Escludi audio originale'],['keep','Mantieni audio'],['duck','Abbassa durante la voce']]})){reads[key]=select(key,items);videoPanel.append(panel.lastElementChild);}
 const input=videoPanel.querySelector('[data-video-file]');videoPanel.querySelector('[data-video-upload]').onclick=()=>input.click();input.onchange=async()=>{try{if(uploadVideo)await uploadVideo([...input.files]);}catch(e){notify(e.message);}finally{input.value='';}};
 const technical=document.createElement('section');technical.className='infographic-advanced';technical.innerHTML='<h3 class="prompt-settings-heading">Regia e audio</h3>';panel.append(technical);
 for(const key of ['frame','palette','shapes','pace','transition','voice_style','music','sfx']){reads[key]=select(key,choices[key]);technical.append(panel.lastElementChild);}
 technical.insertAdjacentHTML('beforeend','<div class="settings-grid"><label class="field"><span>Durata indicativa · secondi</span><input data-info="duration" type="number" min="5" max="120" value="30"></label><label class="field"><span>Scene</span><input data-info="scenes" type="number" min="1" max="8" value="3"></label><label class="field"><span>Voce narrante</span><input data-info="voice" type="checkbox" checked></label><label class="field"><span>Modello immagini</span><select data-info="image_model"><option value="">Predefinito dalle impostazioni</option></select></label></div>');
 $('#prompt-context').append(panel);
 renderScreen();
 return {read:()=>Object.fromEntries([...Object.entries(reads).map(([k,fn])=>[k,fn()]),...[...panel.querySelectorAll('[data-info]')].map(e=>[e.dataset.info,e.type==='checkbox'?e.checked:e.type==='number'?Number(e.value):e.value])]),render:()=>{renderScreen();panel.hidden=$('#lab-tool').value!=='infographic';const clips=getAttachments().filter(m=>m.mime==='video/mp4'),pick=panel.querySelector('[data-info="video_id"]'),previous=pick.value;pick.replaceChildren(...(clips.length?clips.map(m=>new Option(m.name,m.id)):[new Option('Nessun video allegato','')]));pick.value=clips.some(m=>m.id===previous)?previous:clips[0]?.id||'';for(const key of ['video_fit','video_end','video_audio'])videoPanel.querySelector('[data-infographic-field="'+key+'"]').hidden=!clips.length;const select=panel.querySelector('[data-info="image_model"]'),value=select.value,state=getState();if(!state)return;const ids=state.models.filter(m=>m.ready&&m.capabilities.includes('create'));const signature=JSON.stringify(ids.map(m=>[m.id,m.name]));if(select.dataset.signature!==signature){select.dataset.signature=signature;select.replaceChildren(new Option('Predefinito dalle impostazioni',''),...ids.map(m=>new Option(m.name,m.id)));select.value=value;}}};
}

const players=new WeakMap();
export function mountInfographic(target,deck,index,frame,options,value){
 const old=players.get(target);if(old)old();
 const doc=frame.querySelector('iframe')?.contentDocument;if(!doc)return;
 const radius={square:0,soft:48,round:110}[deck.infographic.options?.corners||'square'];frame.style.borderRadius=radius+'px';frame.style.overflow='hidden';
 const duration=deck.infographic.durations[index],panel=document.createElement('section');panel.className='infographic-timeline no-export';
 panel.innerHTML='<strong>Animazione della scena</strong><div class="infographic-player"><button class="btn" data-play>▶ Anteprima</button><input data-time type="range" min="0" max="'+duration+'" value="0" step="0.02" aria-label="Tempo animazione"><output data-clock>0 s</output><button class="btn" data-mp4>Esporta / aggiorna MP4</button></div><details><summary>Tempi ed effetti degli elementi</summary><div data-tracks></div></details><p class="small-note">La modifica grafica mostra tutti gli elementi. L’anteprima applica i tempi; il video esportato include transizioni, voce, musica ed effetti.</p>';
 target.append(panel);const q=s=>panel.querySelector(s);let raf=0,playing=false,start=0,time=0;
 const corners=document.createElement('div');corners.className='infographic-player';
 for(const key of ['corners','frame',...(deck.infographic.videos?.length&&deck.infographic.options?.layout!=='full'?['video_start']:[])]){const label=document.createElement('label');label.textContent=labels[key]+' ';const input=document.createElement('select');input.ariaLabel=labels[key];for(const [id,text] of choices[key])input.append(new Option(text,id));input.value=deck.infographic.options?.[key]||(key==='corners'?'square':key==='frame'?'dark':'together');input.disabled=!options.editable;input.onchange=async()=>{try{deck.infographic.options={...deck.infographic.options,[key]:input.value};await options.onChange(encode(deck));}catch(e){q('[data-clock]').textContent=e.message;}};label.append(input);corners.append(label);}panel.append(corners);
 const sources=new Set([deck.infographic.video?.asset_id,...(deck.infographic.videos||[]).map(v=>v.asset_id)]),movie=[...value.media].reverse().find(m=>m.mime==='video/mp4'&&!sources.has(m.id));if(movie){const label=document.createElement('p');label.className='small-note';label.textContent='Ultimo video esportato. Dopo le modifiche premi «Esporta / aggiorna MP4» per aggiornarlo.';const video=document.createElement('video');video.controls=true;video.preload='metadata';video.src='/media/'+movie.path;video.className='infographic-movie';const link=document.createElement('a');link.href=video.src;link.download=movie.name;link.className='btn';link.textContent='Scarica MP4';panel.append(label,video,link);}
 const specs=deck.infographic.videos||(deck.infographic.video?[deck.infographic.video]:[]),offset=deck.infographic.durations.slice(0,index).reduce((a,b)=>a+b,0);
 const documents=deck.pages.map((page,i)=>i===index?doc:new DOMParser().parseFromString(page.html,'text/html'));H3Motion.videoTracks(documents,deck.infographic);
 const clips=[...doc.querySelectorAll('video[data-h3-video]')].map(element=>({element,spec:specs.find(v=>v.asset_id===element.dataset.h3Video),start:Number(element.dataset.h3VideoStart)||0})).filter(v=>v.spec);
 const syncVideo=(t,moving=playing)=>{for(const {element,spec,start} of clips){if(!Number.isFinite(element.duration))continue;const elapsed=offset+t-start,ended=spec.end!=='loop'&&elapsed>=element.duration-.04,target=elapsed<0?0:spec.end==='loop'?elapsed%element.duration:Math.min(elapsed,Math.max(0,element.duration-.04));if(!moving||elapsed<0||ended||Math.abs(element.currentTime-target)>.18)element.currentTime=target;if(moving&&elapsed>=0&&!ended){if(element.paused)element.play().catch(()=>{});}else element.pause();}};
 for(const {element} of clips)element.addEventListener('loadedmetadata',()=>syncVideo(time));syncVideo(0);
 const apply=t=>{time=t;syncVideo(t);H3Motion.apply(doc,t,duration);q('[data-time]').value=t;q('[data-clock]').textContent=t.toFixed(1)+' / '+duration.toFixed(1)+' s';};
 function stop(){cancelAnimationFrame(raf);for(const {element} of clips)element.pause();playing=false;q('[data-play]').textContent='▶ Anteprima';}
 function tick(now){if(!panel.isConnected){stop();return;}const t=(now-start)/1000;apply(Math.min(t,duration));if(t<duration)raf=requestAnimationFrame(tick);else stop();}
 q('[data-play]').onclick=()=>{if(playing){stop();return;}if(time>=duration)time=0;playing=true;syncVideo(time,true);start=performance.now()-time*1000;q('[data-play]').textContent='Ⅱ Pausa';raf=requestAnimationFrame(tick);};q('[data-time]').oninput=()=>{stop();apply(Number(q('[data-time]').value));};
 q('[data-mp4]').disabled=!options.editable;q('[data-mp4]').onclick=async()=>{try{q('[data-mp4]').disabled=true;await options.api('/canvas/'+options.chatId+'/infographic/render',{artifact_id:value.id});q('[data-mp4]').textContent='Rendering in coda…';}catch(e){q('[data-clock]').textContent=e.message;q('[data-mp4]').disabled=false;}};
 const split=deck.infographic.options?.layout&&deck.infographic.options.layout!=='full';
 const tracks=root=>[...root.querySelectorAll('[data-motion]')].filter(e=>!split||!e.hasAttribute('data-panel'));
 const nodes=tracks(doc);
 for(const [i,node] of nodes.entries()){
  const row=document.createElement('div');row.className='infographic-track';const title=document.createElement('span');title.textContent=(node.textContent.trim()||node.getAttribute('alt')||node.tagName).slice(0,65);row.append(title);
  const effect=document.createElement('select');effect.ariaLabel='Effetto elemento '+(i+1);for(const name of H3Motion.effects)effect.append(new Option(name,name));effect.value=node.dataset.motion;row.append(effect);
  const fields={start:['Ingresso',0],duration:['Durata',.65],out:['Uscita',duration]};
  const inputs={};for(const [key,[label,fallback]] of Object.entries(fields)){const input=document.createElement('input');input.type='number';input.min='0';input.max=duration;input.step='.1';input.value=node.dataset[key]??fallback;input.ariaLabel=label+' elemento '+(i+1);input.title=label+' · secondi';row.append(input);inputs[key]=input;}
  const save=async()=>{stop();const parsed=new DOMParser().parseFromString(deck.pages[index].html,'text/html'),original=tracks(parsed)[i];if(!original)return;original.dataset.motion=effect.value;for(const [key,input] of Object.entries(inputs))original.dataset[key]=String(Math.max(0,Math.min(duration,Number(input.value)||0)));deck.pages[index].html=[...parsed.head.querySelectorAll('style')].map(s=>s.outerHTML).join('')+parsed.body.innerHTML;await options.onChange(encode(deck));};
  for(const input of [effect,...Object.values(inputs)]){input.disabled=!options.editable;input.onchange=()=>save().catch(e=>q('[data-clock]').textContent=e.message);}q('[data-tracks]').append(row);
 }
 players.set(target,stop);
 // Initial view is the complete design; playback is an explicit user action.
}
