import '../static/infographic-motion.js';
const encode=deck=>'```h3-slides\n'+JSON.stringify(deck)+'\n```';
const $=s=>document.querySelector(s);
const choices={corners:[['square','Dritti'],['soft','Morbidi'],['round','Arrotondati']],frame:[['dark','Scuro'],['light','Chiaro']],style:[['auto','Automatico'],['professional','Professionale'],['playful','Giocoso'],['comic','Fumetto'],['editorial','Editoriale'],['advert','Spot'],['tech','Tecnologico']],palette:[['auto','Dal prompt'],['natural','Naturale'],['pastel','Pastello'],['vivid','Vivace'],['neon','Neon'],['dark','Scura']],shapes:[['auto','Automatiche'],['soft','Morbide'],['sharp','Nette'],['mixed','Miste']],pace:[['auto','Automatico'],['calm','Calmo'],['dynamic','Dinamico'],['spot','Energico']],images:[['auto','Automatiche'],['provided','Allegati / galleria'],['generate','Genera con AI']],music:[['auto','Dal prompt'],['none','Nessuna'],['uploaded','Audio allegato'],['generate','Genera base'],['jingle','Jingle cantato']],sfx:[['none','Nessuno'],['subtle','Discreti'],['strong','Marcati']],voice_style:[['auto','Automatica'],['serious','Seria'],['lively','Vivace'],['spot','Spot'],['warm','Calda'],['radio','Radio · +8–12%']],transition:[['auto','Automatiche'],['cut','Taglio'],['fade','Dissolvenza'],['slide','Scorrimento'],['zoom','Zoom'],['wipe','Tendina']],output:[['video','Video animato'],['static','Statica']]};
const labels={corners:'Angoli del video',frame:'Sfondo degli angoli',style:'Stile',palette:'Palette',shapes:'Forme',pace:'Ritmo',images:'Immagini',music:'Musica',sfx:'Effetti sonori',voice_style:'Recitazione',transition:'Transizioni',output:'Risultato'};
export function initInfographics({getState}){
 const panel=document.createElement('section');panel.id='infographic-options';panel.hidden=true;panel.className='prompt-slide-options';
 panel.innerHTML='<p class="small-note">Regia automatica dal prompt e dalle fonti. Aggiungi immagini tue o lascia che vengano generate tutte insieme.</p>';
 const select=(key,items)=>{const field=document.createElement('div');field.className='prompt-field';field.dataset.infographicField=key;field.innerHTML='<span class="prompt-field-label">'+(labels[key]||'Formato')+'</span>';const group=document.createElement('div');group.className='prompt-choices';group.ariaLabel=labels[key]||'Formato';let value=key==='sfx'?'subtle':items[0][0];
  for(const [id,label] of items){const button=document.createElement('button');button.type='button';button.className='prompt-choice';button.textContent=label;button.dataset.value=id;button.setAttribute('aria-pressed',String(id===value));button.onclick=()=>{value=id;for(const b of group.children)b.setAttribute('aria-pressed',String(b===button));};group.append(button);}field.append(group);panel.append(field);return ()=>value;
 };
 const reads={format:select('format',[['9:16','9:16'],['16:9','16:9'],['1:1','1:1'],['4:3','4:3'],['16:10','16:10']])};for(const key of ['style','images','output','corners'])reads[key]=select(key,choices[key]);
 const technical=document.createElement('details');technical.className='infographic-advanced';technical.innerHTML='<summary>Personalizza regia e audio</summary>';panel.append(technical);
 for(const key of ['frame','palette','shapes','pace','transition','voice_style','music','sfx']){reads[key]=select(key,choices[key]);technical.append(panel.lastElementChild);}
 technical.insertAdjacentHTML('beforeend','<div class="settings-grid"><label class="field"><span>Durata indicativa · secondi</span><input data-info="duration" type="number" min="5" max="120" value="30"></label><label class="field"><span>Scene</span><input data-info="scenes" type="number" min="1" max="8" value="3"></label><label class="field"><span>Voce narrante</span><input data-info="voice" type="checkbox" checked></label><label class="field"><span>Modello immagini</span><select data-info="image_model"><option value="">Predefinito dalle impostazioni</option></select></label></div>');
 $('#prompt-context').append(panel);
 return {read:()=>Object.fromEntries([...Object.entries(reads).map(([k,fn])=>[k,fn()]),...[...panel.querySelectorAll('[data-info]')].map(e=>[e.dataset.info,e.type==='checkbox'?e.checked:e.type==='number'?Number(e.value):e.value])]),render:()=>{panel.hidden=$('#lab-tool').value!=='infographic';const select=panel.querySelector('[data-info="image_model"]'),value=select.value,state=getState();if(!state)return;const ids=state.models.filter(m=>m.ready&&m.capabilities.includes('create'));const signature=JSON.stringify(ids.map(m=>[m.id,m.name]));if(select.dataset.signature!==signature){select.dataset.signature=signature;select.replaceChildren(new Option('Predefinito dalle impostazioni',''),...ids.map(m=>new Option(m.name,m.id)));select.value=value;}}};
}

const players=new WeakMap();
export function mountInfographic(target,deck,index,frame,options,value){
 const old=players.get(target);if(old)old();
 const doc=frame.querySelector('iframe')?.contentDocument;if(!doc)return;
 const radius={square:0,soft:48,round:110}[deck.infographic.options?.corners||'square'];frame.style.borderRadius=radius+'px';frame.style.overflow='hidden';
 const duration=deck.infographic.durations[index],panel=document.createElement('section');panel.className='infographic-timeline no-export';
 panel.innerHTML='<strong>Animazione della scena</strong><div class="infographic-player"><button class="btn" data-play>▶ Anteprima</button><input data-time type="range" min="0" max="'+duration+'" value="0" step="0.02" aria-label="Tempo animazione"><output data-clock>0 s</output><button class="btn" data-mp4>Esporta / aggiorna MP4</button></div><details><summary>Tempi ed effetti degli elementi</summary><div data-tracks></div></details><p class="small-note">La modifica grafica mostra tutti gli elementi. L’anteprima applica i tempi; il video esportato include transizioni, voce, musica ed effetti.</p>';
 target.append(panel);const q=s=>panel.querySelector(s);let raf=0,playing=false,start=0,time=0;
 const corners=document.createElement('div');corners.className='infographic-player';
 for(const key of ['corners','frame']){const label=document.createElement('label');label.textContent=labels[key]+' ';const input=document.createElement('select');input.ariaLabel=labels[key];for(const [id,text] of choices[key])input.append(new Option(text,id));input.value=deck.infographic.options?.[key]||(key==='corners'?'square':'dark');input.disabled=!options.editable;input.onchange=async()=>{try{deck.infographic.options={...deck.infographic.options,[key]:input.value};await options.onChange(encode(deck));}catch(e){q('[data-clock]').textContent=e.message;}};label.append(input);corners.append(label);}panel.append(corners);
 const movie=[...value.media].reverse().find(m=>m.mime==='video/mp4');if(movie){const label=document.createElement('p');label.className='small-note';label.textContent='Ultimo video esportato. Dopo le modifiche premi «Esporta / aggiorna MP4» per aggiornarlo.';const video=document.createElement('video');video.controls=true;video.preload='metadata';video.src='/media/'+movie.path;video.className='infographic-movie';const link=document.createElement('a');link.href=video.src;link.download=movie.name;link.className='btn';link.textContent='Scarica MP4';panel.append(label,video,link);}
 const apply=t=>{time=t;H3Motion.apply(doc,t,duration);q('[data-time]').value=t;q('[data-clock]').textContent=t.toFixed(1)+' / '+duration.toFixed(1)+' s';};
 function stop(){cancelAnimationFrame(raf);playing=false;q('[data-play]').textContent='▶ Anteprima';}
 function tick(now){if(!panel.isConnected){stop();return;}const t=(now-start)/1000;apply(Math.min(t,duration));if(t<duration)raf=requestAnimationFrame(tick);else stop();}
 q('[data-play]').onclick=()=>{if(playing){stop();return;}playing=true;start=performance.now()-(time>=duration?0:time)*1000;q('[data-play]').textContent='Ⅱ Pausa';raf=requestAnimationFrame(tick);};q('[data-time]').oninput=()=>{stop();apply(Number(q('[data-time]').value));};
 q('[data-mp4]').disabled=!options.editable;q('[data-mp4]').onclick=async()=>{try{q('[data-mp4]').disabled=true;await options.api('/canvas/'+options.chatId+'/infographic/render',{artifact_id:value.id});q('[data-mp4]').textContent='Rendering in coda…';}catch(e){q('[data-clock]').textContent=e.message;q('[data-mp4]').disabled=false;}};
 const nodes=[...doc.querySelectorAll('[data-motion]')];
 for(const [i,node] of nodes.entries()){
  const row=document.createElement('div');row.className='infographic-track';const title=document.createElement('span');title.textContent=(node.textContent.trim()||node.getAttribute('alt')||node.tagName).slice(0,65);row.append(title);
  const effect=document.createElement('select');effect.ariaLabel='Effetto elemento '+(i+1);for(const name of H3Motion.effects)effect.append(new Option(name,name));effect.value=node.dataset.motion;row.append(effect);
  const fields={start:['Ingresso',0],duration:['Durata',.65],out:['Uscita',duration]};
  const inputs={};for(const [key,[label,fallback]] of Object.entries(fields)){const input=document.createElement('input');input.type='number';input.min='0';input.max=duration;input.step='.1';input.value=node.dataset[key]??fallback;input.ariaLabel=label+' elemento '+(i+1);input.title=label+' · secondi';row.append(input);inputs[key]=input;}
  const save=async()=>{stop();const parsed=new DOMParser().parseFromString(deck.pages[index].html,'text/html'),original=[...parsed.querySelectorAll('[data-motion]')][i];if(!original)return;original.dataset.motion=effect.value;for(const [key,input] of Object.entries(inputs))original.dataset[key]=String(Math.max(0,Math.min(duration,Number(input.value)||0)));deck.pages[index].html=[...parsed.head.querySelectorAll('style')].map(s=>s.outerHTML).join('')+parsed.body.innerHTML;await options.onChange(encode(deck));};
  for(const input of [effect,...Object.values(inputs)]){input.disabled=!options.editable;input.onchange=()=>save().catch(e=>q('[data-clock]').textContent=e.message);}q('[data-tracks]').append(row);
 }
 players.set(target,stop);
 // Initial view is the complete design; playback is an explicit user action.
}
