import {escape as esc} from './render.js';
import {initProjectImports} from './project-imports.js';
import {initProjectRagOptions} from './project-rag-options.js';

export function initProjects({api,getState,getChat,refresh,notify,act,select,showCanvas,pickDirectory}){
 const $=s=>document.querySelector(s);let editId=null,view='sources',open=false,selection=new Map(),rag=new Map(),projectCache=null,last='',selected=null;
 $('#collections').previousElementSibling.insertAdjacentHTML('beforebegin','<div class="side-label">PROGETTI<button id="new-project" aria-label="Crea progetto">＋</button></div><div id="projects"></div>');
 $('#canvas-toggle').insertAdjacentHTML('afterend','<button id="sources-toggle" class="btn" aria-pressed="false">▤ Fonti e file</button>');
 $('#web-toggle').insertAdjacentHTML('beforebegin','<label class="chat-advanced-toggle" title="Usa i documenti del progetto nella risposta"><input type="checkbox" id="rag-enabled" checked> RAG</label><span id="project-chat-label" class="badge"></span>');
 $('#workspace').insertAdjacentHTML('beforeend',`<aside id="knowledge-panel" class="canvas-panel knowledge-panel" hidden aria-label="Fonti e file"><div class="canvas-head"><div><span class="eyebrow">DOCUMENTI E RIFERIMENTI</span><h2>Fonti e file</h2></div><button id="knowledge-close" class="icon-button" aria-label="Chiudi fonti">×</button></div><div class="canvas-toolbar"><div class="segmented"><button data-knowledge-tab="sources" class="active">Fonti</button><button data-knowledge-tab="files">File</button></div><button id="knowledge-canvas" class="text-button">Canvas →</button></div><div id="knowledge-content" class="knowledge-content"></div></aside>`);
 document.body.insertAdjacentHTML('beforeend',`<dialog id="project-dialog" class="settings-dialog project-dialog"><header><div><div class="eyebrow">UNO SPAZIO PER IL TUO LAVORO</div><h2 id="project-dialog-title">Progetto</h2></div><button id="project-close" class="icon-button" aria-label="Chiudi progetto">×</button></header><div class="project-body"><label class="field"><span>Nome</span><input id="project-name" maxlength="80"></label><label class="field"><span>Istruzioni condivise tra le chat</span><textarea id="project-instructions" rows="3" maxlength="8000"></textarea></label><label class="check"><input type="checkbox" id="project-sources-only"> Rispondi solo dalle fonti del progetto quando RAG è attivo</label><section id="project-documents" hidden><h3>Documenti del progetto</h3><p>Collega file o cartelle originali: PDF, Word, testo e codice. I file restano dove sono. Aggiorna per rilevare file nuovi o modificati.</p><label class="field"><span>Percorsi · uno per riga</span><textarea id="project-paths" rows="3" placeholder="F:\\Documenti\\progetto&#10;F:\\Appunti\\note.md"></textarea></label><div class="project-actions"><button id="project-folder" class="btn">Sfoglia cartella</button><button id="project-add" class="btn">Collega e indicizza</button><button id="project-refresh" class="btn">Aggiorna indice</button></div><p id="project-progress" role="status"></p><div id="project-source-list"></div></section><p id="project-error" class="settings-error" role="alert" hidden></p></div><footer><button id="project-delete" class="btn danger">Elimina progetto</button><button id="project-save" class="btn primary">Salva progetto</button></footer></dialog>`);
 const currentProject=()=>getChat()?.project_id;
 function sidebar(selectedId){
   $('#projects').innerHTML=(getState()?.projects||[]).map(p=>`<div class="collection-row"><button data-project="${p.id}" class="${selectedId===p.id?'active':''}">▣ ${esc(p.name)}</button><button data-project-edit="${p.id}" aria-label="Impostazioni ${esc(p.name)}">⋯</button></div>`).join('');
 }
 function controls(){const chat=getChat(),p=getState()?.projects?.find(p=>p.id===chat?.project_id);$('#rag-enabled').disabled=!p;$('#rag-enabled').checked=rag.get(chat?.id)??getState()?.settings.rag_enabled??true;$('#project-chat-label').textContent=p?.name||'Nessun progetto';$('#project-chat-label').title=p?'Istruzioni e fonti condivise nel progetto':'Crea un progetto o sposta qui la chat dal menu ⋯';}
 function read(){const chat=getChat();return {rag:$('#rag-enabled').checked,...(chat?.project_id&&selection.has(chat.project_id)?{rag_sources:selection.get(chat.project_id)}:{})};}
 const error=e=>{$('#project-error').hidden=false;$('#project-error').textContent=e.message;};
 const imports=initProjectImports({api,getProjectId:()=>editId,getToken:()=>getState()?.token||'',getLimits:()=>getState()?.project_limits,showError:error,notify,onChange:async id=>{selection.delete(id);await docs(await api('/projects/'+id));await refresh();}});
 const ragOptions=initProjectRagOptions({host:$('#project-documents'),api,getState,refresh,showError:error,notify});
 async function manage(id=null){editId=id;$('#project-error').hidden=true;$('#project-paths').value='';$('#project-documents').hidden=!id;$('#project-delete').hidden=!id;$('#project-dialog-title').textContent=id?'Impostazioni progetto':'Nuovo progetto';const p=id?await api('/projects/'+id):{};$('#project-name').value=p.name||'';$('#project-instructions').value=p.instructions||'';$('#project-sources-only').checked=!!p.sources_only;$('#project-dialog').showModal();if(id)await docs(p);}
 async function docs(p){if(editId!==p.id)return;imports.controls(p.indexing);const locked=p.indexing||imports.isBusy();ragOptions.render(locked);$('#project-progress').textContent=p.progress?.error||p.progress?.stage||'';$('#project-source-list').innerHTML=(p.roots||[]).map(r=>`<div class="project-source"><div><strong>Cartella collegata</strong><small>${esc(r.path)}</small><span>Aggiornamento automatico dei documenti nuovi e modificati</span></div><button class="text-button" data-unlink-root="${r.id}" ${locked?'disabled':''}>Scollega cartella</button></div>`).join('')+p.sources.map(s=>`<div class="project-source"><div><strong>${esc(s.name)}</strong><small>${esc(s.imported?"Importato nel progetto":s.path)}</small><span>${esc(({ready:'Indicizzato',error:'Errore',pending:'In attesa',indexing:'Indicizzazione'})[s.status])} · ${s.chunks} estratti</span>${s.error?`<p class="small-note">${esc(s.error)}</p>`:''}</div><button class="text-button" data-unlink-source="${s.id}" ${locked?'disabled':''}>Scollega</button></div>`).join('')||'<p>Nessun documento collegato.</p>';$('#project-add').disabled=locked;$('#project-refresh').disabled=locked;$('#project-delete').disabled=locked;for(const b of $('#project-source-list').querySelectorAll('[data-unlink-root]'))b.onclick=act(async()=>{await api('/projects/'+p.id+'/roots/'+b.dataset.unlinkRoot,{},'DELETE');await docs(await api('/projects/'+p.id));notify('Cartella scollegata. I documenti già indicizzati restano disponibili.');});for(const b of $('#project-source-list').querySelectorAll('[data-unlink-source]'))b.onclick=act(async()=>{await api('/projects/'+p.id+'/sources/'+b.dataset.unlinkSource,{},'DELETE');selection.delete(p.id);await docs(await api('/projects/'+p.id));await refresh();});}
 function toggle(value=!open){open=value;$('#knowledge-panel').hidden=!value;$('#sources-toggle').setAttribute('aria-pressed',value);if(value){$('#canvas-panel').hidden=true;$('#workspace').classList.add('has-canvas');return render();}else{return showCanvas(null);}}
 function hide(){open=false;$('#knowledge-panel').hidden=true;$('#sources-toggle').setAttribute('aria-pressed','false');}
 async function render(force=false){
   if(!open)return;const chat=getChat(),id=chat?.project_id;const fetched=id?await api('/projects/'+id):null;if(!open||chat?.id!==getChat()?.id)return;projectCache=fetched;
   const signature=JSON.stringify([chat?.id,chat?.messages,projectCache,selection.get(id),view,selected]);if(signature===last&&!force)return;last=signature;
   const host=$('#knowledge-content');host.innerHTML='';
   if(view==='files'){
     host.innerHTML=`<h3>${esc(projectCache?.name||'File della conversazione')}</h3>${projectCache?'<button id="knowledge-manage" class="btn">Gestisci documenti e indice</button>':''}<div id="knowledge-files"></div>`;if(projectCache)$('#knowledge-manage').onclick=act(()=>manage(id));const list=$('#knowledge-files');
     if(projectCache){const label=document.createElement('p');label.textContent='Fonti da usare nel prossimo messaggio:';list.append(label);for(const s of projectCache.sources){const row=document.createElement('label');row.className='project-source source-choice';row.innerHTML=`<input type="checkbox" ${!selection.has(id)||selection.get(id).includes(s.id)?'checked':''}><span><strong>${esc(s.name)}</strong><small>${esc(s.status)} · ${s.chunks} estratti</small></span>`;row.querySelector('input').onchange=()=>{selection.set(id,[...list.querySelectorAll('[data-source-choice]')].filter(r=>r.querySelector('input').checked).map(r=>r.dataset.sourceChoice));};row.dataset.sourceChoice=s.id;list.append(row);}}
     const seen=new Set();for(const m of chat?.messages||[])for(const file of [...(m.media||[]),...(m.meta?.artifact?.media||[])]){if(seen.has(file.path))continue;seen.add(file.path);const a=document.createElement('a');a.href='/media/'+file.path;a.textContent=file.name;a.className='knowledge-file';a.download=file.name;list.append(a);}if(!projectCache&&!seen.size)list.textContent='Allega un file alla chat oppure crea un progetto.';return;
   }
   const messages=(chat?.messages||[]).filter(m=>m.meta?.rag_sources?.length||m.meta?.web_sources?.length).reverse();
   if(!messages.length){host.innerHTML='<p>Qui appariranno gli estratti RAG e le fonti web utilizzati nelle risposte. Premi Web per cercare online anche senza progetto.</p>';return;}
   for(const message of messages){const section=document.createElement('section');section.className='source-turn';const h=document.createElement('h3');h.textContent=message.meta.prompt?.slice(0,100)||'Fonti della risposta';section.append(h);
     for(const source of message.meta.rag_sources||[]){const card=document.createElement('details');card.className='source-card';card.open=selected?.message===message.id&&selected?.citation===source.citation;const heading=document.createElement('summary');heading.textContent='['+source.citation+'] '+source.name+' · '+source.location;const excerpt=document.createElement('p');excerpt.className='source-excerpt';const mark=document.createElement(card.open?'mark':'span');mark.textContent=source.text;excerpt.append(mark);card.append(heading,excerpt);if(source.image){const a=document.createElement('a');a.href='/media/'+source.image.path;a.target='_blank';a.rel='noopener';const img=document.createElement('img');img.src=a.href;img.alt=source.image.name;img.loading='lazy';img.style.maxWidth='100%';a.append(img);card.append(a);}if(source.url){const a=document.createElement('a');a.href=source.url;a.target='_blank';a.rel='noopener';a.textContent='Apri pagina originale';card.append(a);}section.append(card);if(card.open)setTimeout(()=>card.scrollIntoView({block:'nearest'}),0);}
     for(const source of message.meta.web_sources||[]){const card=document.createElement('details');card.className='source-card';const heading=document.createElement('summary');heading.textContent=source.title+(source.read?' · pagina letta':' · solo estratto');const a=document.createElement('a');a.href=source.url;a.target='_blank';a.rel='noopener';a.textContent=source.url;const p=document.createElement('p');p.textContent=source.text||source.snippet;card.append(heading,a,p);section.append(card);}
     if(projectCache&&message.meta.web_sources?.length){const b=document.createElement('button');b.className='btn small';b.textContent='Salva fonti web nel progetto';b.onclick=act(async()=>{await api('/projects/'+id+'/web-sources',{message_id:message.id});notify('Fonti salvate. Indicizzazione in corso.');await refresh();});section.append(b);}host.append(section);
   }
 }
 function citation(source,sources,message){selected={message:message.id,citation:source.citation};view='sources';for(const b of document.querySelectorAll('[data-knowledge-tab]'))b.classList.toggle('active',b.dataset.knowledgeTab===view);toggle(true);}
 function append(target,message){if(!message.meta?.rag_sources&&!message.meta?.web_sources?.length)return;const row=document.createElement('div');row.className='source-pills';for(const source of message.meta.rag_sources||[]){const b=document.createElement('button');b.className='text-button rag-citation';b.textContent='['+source.citation+'] '+source.name+' · '+source.location;b.onclick=()=>citation(source,message.meta.rag_sources,message);row.append(b);}if(message.meta.rag_sources&&!message.meta.rag_sources.length){const note=document.createElement('span');note.textContent='RAG: nessun estratto pertinente trovato.';row.append(note);}if(message.meta.rag_visual_warning){const note=document.createElement('span');note.className='small-note';note.textContent=message.meta.rag_visual_warning;row.append(note);}if(message.meta.invalid_citations?.length){const p=document.createElement('p');p.className='render-error';p.textContent='Alcuni riferimenti prodotti dal modello non corrispondono alle fonti disponibili.';row.append(p);}if(message.meta.web_sources?.length){const b=document.createElement('button');b.className='text-button';b.textContent=message.meta.web_sources.length+' fonti web';b.onclick=()=>{selected=null;view='sources';toggle(true);};row.append(b);}target.append(row);}
 async function poll(){if($('#project-dialog').open&&editId)await docs(await api('/projects/'+editId));if(open)await render();}
 $('#new-project').onclick=act(()=>manage());$('#projects').onclick=act(async e=>{const p=e.target.closest('[data-project]'),edit=e.target.closest('[data-project-edit]');if(edit)await manage(edit.dataset.projectEdit);else if(p)select(p.dataset.project);});
 $('#project-close').onclick=()=>$('#project-dialog').close();$('#project-save').onclick=async()=>{const b=$('#project-save');b.disabled=true;try{const p=await api('/projects'+(editId?'/'+editId:''),{name:$('#project-name').value,instructions:$('#project-instructions').value,sources_only:$('#project-sources-only').checked},editId?'PATCH':'POST');editId=p.id;$('#project-documents').hidden=false;$('#project-delete').hidden=false;$('#project-dialog-title').textContent='Impostazioni progetto';$('#project-error').hidden=true;await docs(p);await refresh();select(p.id);notify('Progetto salvato. Collega ora i documenti oppure chiudi per iniziare una chat.');}catch(e){error(e);}finally{b.disabled=false;}};
 $('#project-folder').onclick=act(()=>pickDirectory('',path=>{$('#project-paths').value+=($('#project-paths').value?'\n':'')+path;}));
 $('#project-add').onclick=async()=>{try{await api('/projects/'+editId+'/sources',{paths:$('#project-paths').value.split('\n').map(s=>s.trim()).filter(Boolean)});$('#project-paths').value='';selection.delete(editId);await docs(await api('/projects/'+editId));await refresh();}catch(e){error(e);}};
 $('#project-refresh').onclick=async()=>{try{await api('/projects/'+editId+'/refresh',{});await docs(await api('/projects/'+editId));}catch(e){error(e);}};
 $('#project-delete').onclick=async()=>{try{const id=editId;await api('/projects/'+id,{},'DELETE');$('#project-dialog').close();selection.delete(id);select(null);await refresh();notify('Progetto eliminato; le chat e i file originali restano disponibili.');}catch(e){error(e);}};
 $('#sources-toggle').onclick=act(()=>toggle());$('#knowledge-close').onclick=()=>toggle(false);$('#knowledge-canvas').onclick=act(()=>{hide();showCanvas(true);});$('#rag-enabled').onchange=()=>rag.set(getChat()?.id,$('#rag-enabled').checked);
 for(const b of document.querySelectorAll('[data-knowledge-tab]'))b.onclick=act(()=>{view=b.dataset.knowledgeTab;for(const c of document.querySelectorAll('[data-knowledge-tab]'))c.classList.toggle('active',c===b);return render(true);});
 return {sidebar,controls,read,manage,poll,hide,citation,append};
}
